# Generated by Django 5.2.1 on 2025-06-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_customer_email_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
    ]
