# Generated by Django 5.2.3 on 2025-06-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_customer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
