# Generated by Django 5.2.3 on 2025-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
