# Generated by Django 5.2.1 on 2025-06-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaggedItems",
            new_name="TaggedItem",
        ),
    ]
